version: '3.9'

services:
  postgresql_db:
    image: postgres:12.18-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: ERaNGEnTeOIn
      POSTGRES_DB: keycloak_database
      POSTGRES_ROOT_PASSWORD: eoWSpoSACHIP
    volumes:
      - kc-pg-volume:/var/lib/postgresql/data
    networks:
      - kc-network
  keycloak_instance:
    image: quay.io/keycloak/keycloak:24.0.1
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql_db/keycloak_database
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: ERaNGEnTeOIn
    ports:
      - 8080:8080
    depends_on:
      - postgresql_db
    networks:
      - kc-network
    command:
      - start-dev
networks:
  kc-network:

volumes:
  kc-pg-volume: